package constant

const (
	ContextGtp = "contextgtp"

	ContextStorageRoot = "contextstorageroot"
	ContextDb          = "contextdb"
	ContextDb1         = "contextdb1"
	ContextDb2         = "contextdb2"

	ContextUser           = "contextuser"
	ContextOsType         = "contextostype"
	ContextAppVersion     = "contextappversion"
	ContextAppKey         = "contextappkey"
	ContextInstallationId = "contextinstallationid"
	ContextAppId          = "contextappid"
	ContextVersionId      = "contextversionid"
	ContextChannel        = "contextchannel"
	ContextAdmin          = "contextadmin"
	ContextAdminId        = "contextadminid"
	ContextAdminName      = "contextadminname"
	ContextToken          = "contexttoken"
	ContextUserTokenId    = "contextusertokenid"
	ContextOpenId         = "contextopenid"
	ContextUserBind       = "contextuserbind"
	ContextModuleAccess   = "contextmoduleaccess"
	ContextRequestBody    = "contextrequestbody"
	ContextTableName      = "contexttablename"
	ContextOperationType  = "contextoperationtype"
	ContextOldValue       = "contextoldvalue"
	ContextNewValue       = "contextnewvalue"
	ContextError          = "contexterror"
	ContextScopeBody      = "contextscopebody"
	ContextScope          = "contextscope"
	ContextSolr           = "contextsolr"
	ContextMqttClient     = "contextmqttclient"
)
